### ISSUE TITLE
 Error: LinkageError occurred while loading main class com.github.bitfexl.stockfishconnector.StockfishServer

### ISSUE THREAD

**Issue by radtya** [bitfexl/lichess-bot-V3#1]
java -jar stockfishconnector.jar
Error: LinkageError occurred while loading main class com.github.bitfexl.stockfishconnector.StockfishServer
	java.lang.UnsupportedClassVersionError: com/github/bitfexl/stockfishconnector/StockfishServer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

**Comment by bitfexl** [comment]
Use Java17:
https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html
